<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.brinkus.labs</groupId>
        <artifactId>labs-parent</artifactId>
        <version>1.1.0</version>
    </parent>

    <groupId>com.brinkus.labs</groupId>
    <artifactId>neo4j-health-check-plugin</artifactId>
    <version>5.26.0</version>
    <packaging>jar</packaging>

    <name>neo4j-health-check-plugin</name>
    <description>Health Check Plugin for Neo4j</description>
    <url>https://github.com/bbrinkus/neo4j-health-check-plugin.git</url>

    <licenses>
        <license>
            <name>GNU General Public License (GPL) version 3.0</name>
            <url>http://www.gnu.org/licenses/</url>
            <distribution>repo</distribution>
            <comments>
                Copyright (C) 2016 Balazs Brinkus

                This program is free software; you can redistribute it and/or modify
                it under the terms of the GNU General Public License as published by
                the Free Software Foundation; either version 3 of the License, or
                (at your option) any later version.

                This program is distributed in the hope that it will be useful,
                but WITHOUT ANY WARRANTY; without even the implied warranty of
                MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
                GNU General Public License for more details.

                You should have received a copy of the GNU General Public License
                along with this program. If not, see http://www.gnu.org/licenses/.
            </comments>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/bbrinkus/neo4j-health-check-plugin</url>
        <connection>scm:git:git://github.com/neo4j-health-check-plugin.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/neo4j-health-check-plugin.git</developerConnection>
    </scm>

    <developers>
        <developer>
            <name>Balazs Brinkus</name>
            <email>balazs@brinkus.com</email>
            <url>http://www.brinkus.com</url>
        </developer>
    </developers>

    <properties>
        <!-- Dependencies versions -->
        <hamcrest.version>3.0</hamcrest.version>
        <jackson.version>2.18.3</jackson.version>
        <junit.version>5.11.4</junit.version>
        <mockito.version>5.16.1</mockito.version>
        <neo4j.version>5.26.0</neo4j.version>
        <slf4j.version>1.7.36</slf4j.version>
        <maven-surefire-plugin.version>3.1.2</maven-surefire-plugin.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>server-api</artifactId>
            <version>${neo4j.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-library</artifactId>
            <version>${hamcrest.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.neo4j.test</groupId>
            <artifactId>neo4j-harness</artifactId>
            <version>${neo4j.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <sourceDirectory>src/main/java</sourceDirectory>
        <testSourceDirectory>src/test/java</testSourceDirectory>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>false</filtering>
            </testResource>
        </testResources>

        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <finalName>neo4j-health-check</finalName>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>
